Vizzuality/afoco

client/package.json, client/src/app/countries/[slug]/page.tsx, client/src/app/countries/page.tsx, client/src/app/datasets/page.tsx, client/src/app/layout.tsx, client/src/app/projects/[slug]/page.tsx, client/src/app/projects/page.tsx, client/src/components/ui/drawer.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/detail/panel.tsx
- Adding dashboard as page element (not dialog)
- Remove `Panel` from Root layout as it has children and we need to scale pages.
=> [FE]: dashboard

client/cypress/e2e/map.cy.ts, client/cypress/e2e/navigation.cy.ts, client/src/app/(landing)/projects/page.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/countries/item.tsx, client/src/containers/projects/detail/constants.ts, client/src/containers/projects/detail/panel.tsx
[Figma design](https://www.figma.com/file/luYbImpyPoLDFF0EeYXV7x/Afoco---Design-%5BInternal%5D?node-id=2075%3A18062&mode=dev)
=> [FE](styles): location tooltip on project detail

client/src/components/ui/combobox.tsx, client/src/components/ui/popover.tsx, client/src/components/ui/slider.tsx, client/src/containers/filters/index.tsx, client/src/containers/map/legend/index.tsx, client/src/containers/map/settings/manager/index.tsx, client/src/containers/projects/list.tsx, client/src/styles/globals.css
=> [FE](fix): fixes

client/src/components/ui/dialog.tsx, client/src/containers/countries/detail/constants.tsx, client/src/containers/countries/detail/panel.tsx
[AF-60](https://vizzuality.atlassian.net/browse/AF-60)
[AF-60]: https://vizzuality.atlassian.net/browse/AF-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](styles): country info modal [AF-60]

infrastructure/afoco_source_bundle/proxy/conf.d/afoco.conf, infrastructure/base/modules/beanstalk/main.tf
Adds a dedicated /health endpoint for the application load balancer
=> Dedicated healtcheck endpoint

infrastructure/afoco_source_bundle/proxy/conf.d/afoco.conf
Trying again to fix the healthchecks in steps, just adding the health endpoint to nginx confix here
=> Adds health endpoint to nginx template

infrastructure/base/modules/beanstalk/main.tf
Beanstalk configuration for custom health endpoint
=> Beanstalk configuration for custom health endpoint

client/src/app/(landing)/countries/page.tsx, client/src/app/(landing)/datasets/page.tsx, client/src/app/(landing)/projects/page.tsx, client/src/containers/countries/item.tsx, client/src/containers/countries/list.tsx, client/src/containers/panel/index.tsx, client/src/containers/projects/detail/panel.tsx
Search country by name and add project count to Country Item in list. 
[Figma](https://www.figma.com/file/luYbImpyPoLDFF0EeYXV7x/Afoco---Design-%5BInternal%5D?node-id=2553%3A40356&mode=dev)
[AF-62](https://vizzuality.atlassian.net/browse/AF-62)
[AF-62]: https://vizzuality.atlassian.net/browse/AF-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](feat): search country by name

client/cypress/e2e/navigation.cy.ts, client/package.json, client/src/containers/datasets/layers/index.tsx, client/src/containers/datasets/layers/land-degradation/hooks.tsx, client/src/containers/datasets/layers/land-degradation/layer.tsx, client/src/containers/datasets/layers/land-degradation/legend.tsx, client/src/containers/datasets/layers/projects/legend.tsx, client/src/containers/legend-settings/index.tsx, client/src/containers/map/legend/index.tsx, client/src/containers/map/legend/item.tsx, cms/package.json
=> land degradation layer

client/src/containers/datasets/layers/biomass-density/layer.tsx, client/src/containers/datasets/layers/biomass-density/legend.tsx, client/src/containers/datasets/layers/biomass-density/mock.json, client/src/containers/datasets/layers/biomass-density/settings.tsx, client/src/containers/datasets/layers/index.tsx, client/src/containers/datasets/layers/net-forest-carbon-flux/layer.tsx, client/src/containers/datasets/layers/net-forest-carbon-flux/legend.tsx, client/src/containers/datasets/layers/net-forest-carbon-flux/mock.json, client/src/containers/datasets/layers/net-forest-carbon-flux/settings.tsx
=> Af 69 fe contextual layers net forest carbon flux

client/src/containers/projects/item.tsx, client/src/containers/sidebar/index.tsx, client/src/store/index.ts
Go to countries, select projects layer, navigate to a country detail page from map and check if tab selected in sidebar is projects.
[AF-88](https://vizzuality.atlassian.net/browse/AF-88)
[AF-88]: https://vizzuality.atlassian.net/browse/AF-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](fix): navigation bug

client/cypress/e2e/navigation.cy.ts, client/src/app/(landing)/projects/page.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/projects/stats.tsx
[AF-73](https://vizzuality.atlassian.net/browse/AF-73)
[AF-73]: https://vizzuality.atlassian.net/browse/AF-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](fix): minor fixes

client/src/components/ui/combobox.tsx, client/src/components/ui/select.tsx, client/src/containers/filters/content.tsx, client/src/containers/projects/item.tsx
[AF-79](https://vizzuality.atlassian.net/browse/AF-79)
[AF-79]: https://vizzuality.atlassian.net/browse/AF-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](styles): country select on filters

client/src/containers/countries/detail/constants.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/countries/item.tsx, client/src/containers/map/index.tsx, client/src/containers/map/settings/manager/index.tsx, client/src/hooks/datasets/index.ts, client/src/hooks/datasets/query-parsers.ts, client/src/hooks/datasets/sync-query.ts
_Previous map styles were pulled from the scaffold so when trying to get label modification it wasn't working_
This PR
---
=> afoco basemap

client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/stats.tsx
=> info stats

client/src/containers/countries/list.tsx, client/src/containers/datasets/list.tsx, client/src/containers/projects/list.tsx
[AF-102](https://vizzuality.atlassian.net/browse/AF-102)
[AF-102]: https://vizzuality.atlassian.net/browse/AF-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](fix): search improvements [AF-102]

client/src/containers/countries/detail/panel.tsx, client/src/styles/globals.css
=> [FE](fix): add class for links in markdown country descriptions

client/package.json, client/src/containers/charts/bar.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/stats.tsx, client/tailwind.config.js
[AF-98](https://vizzuality.atlassian.net/browse/AF-98)
[AF-98]: https://vizzuality.atlassian.net/browse/AF-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](feat): dynamic chart axis [AF-98]

client/cypress/e2e/share.cy.ts, client/src/components/ui/loader.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/countries/list.tsx, client/src/containers/datasets/list.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/projects/list.tsx, client/src/containers/projects/stats.tsx
[AF-93](https://vizzuality.atlassian.net/browse/AF-93)
[AF-93]: https://vizzuality.atlassian.net/browse/AF-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](feat): data loaders [AF-93]

client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/stats.tsx
=> [FE](fix): add intervention area total

client/src/containers/charts/single-bar.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/stats.tsx
=> [FE](feat): tooltips

client/src/containers/charts/single-bar.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/detail/dashboard.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/projects/stats.tsx
=> [FE](fix): harcoded units

client/package.json, client/src/containers/countries/index.tsx, client/src/containers/countries/item.tsx, client/src/containers/countries/list.tsx, client/src/containers/map/legend/item.tsx, client/src/containers/projects/list.tsx, package.json, yarn.lock
=> [FE](fix): projects list and order countries

client/src/app/(landing)/countries/page.tsx, client/src/app/(landing)/projects/page.tsx, client/src/components/ui/scroll-area.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/countries/list.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/projects/list.tsx, client/src/containers/projects/stats.tsx
[Figma](https://www.figma.com/file/luYbImpyPoLDFF0EeYXV7x/Afoco---Design-%5BInternal%5D?type=design&mode=design&t=J9gP8Z9KFX5WmrNS-0)
[AF-104](https://vizzuality.atlassian.net/browse/AF-104)
[AF-104]: https://vizzuality.atlassian.net/browse/AF-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](styles): scroll bar

client/src/containers/filters/badge.tsx, client/src/containers/filters/content.tsx, client/src/containers/filters/selected.tsx
=> [FE](fix): fixes 2

client/cypress/e2e/filters.cy.ts, client/src/components/ui/button.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/filters/content.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/share/index.tsx
=> [FE](styles): project detail header btns

client/src/containers/datasets/list.tsx
[AF-122](https://vizzuality.atlassian.net/browse/AF-122)
[AF-122]: https://vizzuality.atlassian.net/browse/AF-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](fix): add scroll area to datasets panel list [AF-122]

client/src/app/(landing)/projects/page.tsx, client/src/containers/countries/list.tsx, client/src/containers/datasets/layers/projects/hooks.tsx, client/src/containers/panel/index.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/projects/list.tsx, client/src/containers/projects/tabs.tsx, client/src/hooks/datasets/query-parsers.ts, client/src/hooks/datasets/sync-query.ts
=> [FE](feat): add tab to url [AF-127]

client/src/app/(landing)/datasets/page.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/datasets/list.tsx, client/src/containers/share/index.tsx
[AF-128](https://vizzuality.atlassian.net/browse/AF-128)
[AF-128]: https://vizzuality.atlassian.net/browse/AF-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](fix): [AF-128]

client/src/components/ui/tabs.tsx
[AF-135](https://vizzuality.atlassian.net/browse/AF-135)
[AF-135]: https://vizzuality.atlassian.net/browse/AF-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE](styles): tabs hover state [AF-135]

client/src/containers/datasets/layers/projects/hooks.tsx
=> fix pathname in projects

client/src/containers/charts/single-bar.tsx, client/src/containers/countries/detail/constants.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/projects/stats.tsx
=> useful links update

cms/src/api/project/content-types/project/schema.json
=> projects bbox

client/src/containers/datasets/layers/land-degradation/layer.tsx, client/src/containers/datasets/layers/projects/layer.tsx
=> new ids layers

client/src/app/(landing)/countries/page.tsx, client/src/app/(landing)/datasets/page.tsx, client/src/app/(landing)/projects/page.tsx, client/src/components/ui/loader.tsx, client/src/components/ui/scroll-area.tsx, client/src/containers/countries/detail/panel.tsx, client/src/containers/countries/list.tsx, client/src/containers/datasets/list.tsx, client/src/containers/map/index.tsx, client/src/containers/map/legend/index.tsx, client/src/containers/projects/detail/panel.tsx, client/src/containers/projects/list.tsx, client/src/containers/projects/stats.tsx, client/src/containers/projects/tabs.tsx
_Static heights removed and._
_Scroll area adjustmets._
_[AF-155](https://vizzuality.atlassian.net/browse/AF-155?atlOrigin=eyJpIjoiZmMyMmQ5YzMxMjdmNDc0ZWIwZTY2MTQ3OTNhNzdhZTAiLCJwIjoiaiJ9)_
---
to the deploy checklist 
[AF-155]: https://vizzuality.atlassian.net/browse/AF-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> static height removed

client/cypress/e2e/navigation.cy.ts, client/src/containers/map/index.tsx, client/src/hooks/datasets/query-parsers.ts
=> map bounds changed

client/src/app/(landing)/projects/page.tsx, client/src/containers/countries/detail/constants.tsx
=> AFoCO typos

client/src/containers/datasets/layers/projects/hooks.tsx
=> project's layer line

client/next.config.mjs
=> images route

client/Dockerfile.prod
=> adds public folder to Docker image

client/Dockerfile.prod
=> [N/A] fixes missing images from Strapi

client/Dockerfile.prod
=> staging <- develop

client/next.config.mjs
=> images route next config
